# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35a0c5dbc2514deec3a63540971a37892f1026bf3ae9c65d1635fa475ed70c608f0d9b92f49457842bc2a8e1e4b5771f54b2d75224e4461bdedb1c6fed8dc10e

test:
  secret_key_base: 895f709e313b84cd168584f58cc4d66aff0dd164c4fd9d19a6c69621cc135fff7430a88db6e7a3ab5044d04fad328d4901fdf2de36a7a226707969562cc3a2db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
